@CosmicObserverAPI_HostAddress = https://localhost:7047

GET {{CosmicObserverAPI_HostAddress}}/api/Events

###

GET {{CosmicObserverAPI_HostAddress}}/api/Events/11

###

GET {{CosmicObserverAPI_HostAddress}}/api/Events/date?date=2026-04-24

###

GET {{CosmicObserverAPI_HostAddress}}/api/Events/dates?startDate=2000-01-01&endDate=2000-01-07

###

DELETE {{CosmicObserverAPI_HostAddress}}/api/Events/11

###