// <auto-generated />
using System;
using CosmicObserverAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CosmicObserverAPI.Migrations
{
    [DbContext(typeof(CosmicDbContext))]
    [Migration("20260329193821_UpdateEventDateToDateOnly")]
    partial class UpdateEventDateToDateOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("CosmicLogCosmicTag", b =>
                {
                    b.Property<int>("LogsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LogsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("CosmicLogCosmicTag");
                });

            modelBuilder.Entity("CosmicObserverAPI.Models.CosmicEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CosmicEvents");
                });

            modelBuilder.Entity("CosmicObserverAPI.Models.CosmicLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CosmicEventId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CosmicEventId");

                    b.ToTable("CosmicLogs");
                });

            modelBuilder.Entity("CosmicObserverAPI.Models.CosmicTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CosmicTags");
                });

            modelBuilder.Entity("CosmicLogCosmicTag", b =>
                {
                    b.HasOne("CosmicObserverAPI.Models.CosmicLog", null)
                        .WithMany()
                        .HasForeignKey("LogsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosmicObserverAPI.Models.CosmicTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CosmicObserverAPI.Models.CosmicLog", b =>
                {
                    b.HasOne("CosmicObserverAPI.Models.CosmicEvent", "CosmicEvent")
                        .WithMany()
                        .HasForeignKey("CosmicEventId");

                    b.Navigation("CosmicEvent");
                });
#pragma warning restore 612, 618
        }
    }
}
